version: '3.7'

volumes: 
    dynamodb_data:

services:
    dynamodb-local:
      image: amazon/dynamodb-local:latest
      container_name: dynamodb-local
      command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
      volumes: 
        - /tmp:/home/dynamodblocal/data
      ports:
       - "8000:8000"
    contact-form:
        depends_on: 
            - dynamodb-local
        build: .
        ports: 
            - "5000:5000"
        volumes: 
            - .:/src
