version: '3.7'


services:
    localstack:
        container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
        image: localstack/localstack
        ports:
            - "4566-4599:4566-4599"
            - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
        environment:
            - SERVICES=dynamodb,ses
            - DATA_DIR=/tmp/localstack/data
            - PORT_WEB_UI=${PORT_WEB_UI- }
            - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
            - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
            - DOCKER_HOST=unix:///var/run/docker.sock
            - HOST_TMP_FOLDER=/tmp
            - HOSTNAME=localstack
        volumes:
            - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
    contact-form:
        depends_on: 
            - localstack
        build: .
        command: ["./wait-for-it.sh", "localstack:4569", "--", "python", "run-local.py"]
        ports: 
            - "5000:5000"
        environment:
            FLASK_APP: application:create_app('config.LocalConfig')
            FLASK_ENV: development
        volumes: 
            - .:/src
