# Generated by Django 3.0.3 on 2020-06-18 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('ref_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Your e-mail address', max_length=254)),
                ('name', models.CharField(help_text='Your name', max_length=100)),
                ('subject', models.CharField(help_text='Subject', max_length=200)),
                ('message', models.TextField(help_text='Leave your message here')),
                ('attended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_record', models.TextField()),
            ],
        ),
    ]
