# Generated by Django 3.0.3 on 2020-06-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdata',
            name='access_record',
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
