# Generated by Django 3.0.3 on 2020-06-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200618_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdata',
            old_name='ref_number',
            new_name='ref_hash',
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='message',
            field=models.TextField(max_length=10000),
        ),
    ]
