name: CI/CD

on: push

jobs:
  
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build docker images
              run: |
                docker-compose pull
                docker-compose build

            - name: Run tests
              run: |
                docker-compose run contact-form ./wait-for-it.sh localstack:4569 -- pytest --cov -x

    deploy:
      name: Deploy staging
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - uses: actions/setup-python@v2
          with:
            python-version: '3.8'

        - name: Requirements
          run: |
            python3 -m venv env
            source env/bin/activate
            pip install -r requirements.txt
        
        - name: list files
          run: |
            find .

