name: CI/CD

on: push

jobs:
  
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build docker images
              run: |
                docker-compose pull
                docker-compose build

            - name: Run tests
              run: |
                docker-compose run contact-form ./wait-for-it.sh localstack:4569 -- pytest --cov -x

