name: CI Testing

on: 
  push:
    ranches-ignore:
      - master
      - development

jobs:
  
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build docker images
              run: |
                docker-compose pull
                docker-compose build

            - name: Run tests
              run: |
                docker-compose run contact-form ./wait-for-it.sh localstack:4569 -- flask dynamodb create
                docker-compose run contact-form ./wait-for-it.sh localstack:4569 -- pytest --cov -x

    test-build:
      name:  Build JS client
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Setup node
          uses: actions/setup-node@v1
          with:
            node-version: 10.x
        
        - name: Build scripts
          run: |
            cd jsclient
            yarn install
            yarn run prod
